apiVersion: v1
kind: Service
metadata:
  name: {{ include "persona.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "persona.name" . }}
    helm.sh/chart: {{ include "persona.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  selector:
    app: persona
  ports:
  - protocol: TCP
    port: 2345
    targetPort: 8000
    nodePort: 31313